services:
  app:
    build: .
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:8080"
    env_file: .env
  db:
    image: mariadb
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=1
      - MARIADB_USER=user
      - MARIADB_PASSWORD=password
      - MARIADB_DATABASE=app
